version: '3.3'

services:
  app:
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '${PORT}': '${PORT}'
    deploy:
      replicas: 2
    depends_on:
      - cache
  cache:
    image: bitnami/redis:latest
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /data:/bitnami/redis/data