version: '3.3'

services:
  app:
    build: ./
    restart: unless-stopped
    env_file: ./.env
    deploy:
      replicas: 2
  peer:
    container_name: peer
    image: peerjs/peerjs-server
    ports:
      - '9000:9000'
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - cache
    image: nginx:latest
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    volumes:
      - ./nginx:/etc/nginx/templates
    environment:
      - 'NGINX_PORT=${NGINX_PORT}'
      - 'PORT=${PORT}'
    restart: always
  cache:
    image: bitnami/redis:latest
    restart: always
    ports:
      - '6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /data:/bitnami/redis/data