version: '3.8'

services:
  app:
    build: ./
    restart: unless-stopped
    env_file: ./.env
    deploy:
      replicas: 2
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always
